### ISSUE TITLE
Возможность вызвать StackPop для пустого стека

### ISSUE THREAD

**Issue by Gaussiandra** [kirilliliych/Stack#1]
```
int main()
{
    Stack_t stack = {};

    STACK_CONSTRUCT(stack, 1);

    for (int i = 0; i < 10; ++i) {
        StackPush(&stack, i);
    }

    //stack.size = 5;

    for (int i = 0; i < 11; ++i) {
        printf("%d\n", StackPop(&stack));
    }

    return 0;
}
```

Приведёт к ошибке free(): double free detected in tcache 2 и последующему SIGABRT

![Снимок экрана от 2021-10-03 14-13-01](https://user-images.githubusercontent.com/34653515/135751161-dfefb147-916b-4a03-b3e4-a9220d955719.png)

**Comment by h0lycookie** [comment]
Да, действительно существовала такая проблема.

**Comment by h0lycookie** [comment]
Исправил, issue закрыт.
