### ISSUE TITLE
Возможность вызвать деструктор дважды

### ISSUE THREAD

**Issue by Gaussiandra** [kirilliliych/Stack#2]
```
int main()
{
    Stack_t stack = {};

    STACK_CONSTRUCT(stack, 1);

    int value = 20;

    for (int i = 0; i < 11; ++i)
    {
        StackPush(&stack, &i);
    }

    for (int i = 0; i < 9; i++)
    {
        StackPop(&stack);
    }

    StackDtor(&stack);
    StackDtor(&stack);

    return 0;
}
```
Приведёт к двойной очистке памяти и SIGABRT.

![Снимок экрана от 2021-10-07 03-22-20](https://user-images.githubusercontent.com/34653515/136301416-84cb9f95-b080-4bc1-8707-aea36cc3b46d.png)

**Comment by h0lycookie** [comment]
Хорошо подмечено, проблема исправлена. При вызове StackDtor добавлен вызов ASSERT_OK в его начале.
